from typing import List, Tuple

def read_matrix_from_string(input_string: str) -> List[List[str]]:
    """read input and transform it as matrix """
    print("Reading matrix from input string:\n")
    lines = input_string.strip().split("\n")
    matrix = [list(line) for line in lines]
    return matrix

def print_matrix(matrix: List[List[str]]) -> None:
    """print a matrix"""
    print("\nThe matrix is:")
    for row in matrix:
        print(''.join(row))

def find_areas(matrix: List[List[str]]) -> List[Tuple[str, List[Tuple[int, int]]]]:
    visited = [[False for _ in row] for row in matrix]
    areas = []

    def dfs(x, y, letter, current_area):
        if x < 0 or y < 0 or x >= len(matrix) or y >= len(matrix[0]):
            return
        if visited[x][y] or matrix[x][y] != letter:
            return

        visited[x][y] = True
        current_area.append((x, y))

        # Explore 4-connected neighbors
        dfs(x + 1, y, letter, current_area)
        dfs(x - 1, y, letter, current_area)
        dfs(x, y + 1, letter, current_area)
        dfs(x, y - 1, letter, current_area)

    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if not visited[i][j]:
                current_area = []
                dfs(i, j, matrix[i][j], current_area)
                if current_area:
                    areas.append((matrix[i][j], current_area))

    return areas

def calculate_area(positions: List[Tuple[int, int]]) -> int:
    return len(positions)

def calculate_perimeter(matrix: List[List[str]], positions: List[Tuple[int, int]]) -> int:
    perimeter = 0
    rows, cols = len(matrix), len(matrix[0])

    for x, y in positions:
        # Check all 4 sides (up, down, left, right)
        if x == 0 or matrix[x - 1][y] != matrix[x][y]:
            perimeter += 1  # Top
        if x == rows - 1 or matrix[x + 1][y] != matrix[x][y]:
            perimeter += 1  # Bottom
        if y == 0 or matrix[x][y - 1] != matrix[x][y]:
            perimeter += 1  # Left
        if y == cols - 1 or matrix[x][y + 1] != matrix[x][y]:
            perimeter += 1  # Right

    return perimeter


def calculate_sides(matrix: List[List[str]], positions: List[Tuple[int, int]]) -> int:
    sides = 0
    rows, cols = len(matrix), len(matrix[0])
    last_calculated = [False, False, False, False]
    last_x_calculated = [False, False, False, False]
    for i in range(0, rows - 1):
        last_calculated = last_x_calculated
        last_x_calculated
        for j in range(0, cols - 1):
            condition = find_first_by_filter(positions, lambda x,y: x == i and y == j)
            if(condition):
                x = i
                y = j
                previous = last_calculated[0]
                last_calculated[0] = False
                # Count only sides touching the boundary or a different letter
                if x == 0 or matrix[x - 1][y] != matrix[x][y]:
                    last_calculated[0] = True
                    if not previous:
                        sides += 1  # Top
                
                previous = last_calculated[1]
                last_calculated[1] = False
                if x == rows - 1 or matrix[x + 1][y] != matrix[x][y]:
                    last_calculated[1] = True
                    if not previous:
                        sides += 1  # Bottom

                previous = last_calculated[2]
                last_calculated[2] = False
                if y == 0 or matrix[x][y - 1] != matrix[x][y]:
                    last_calculated[2] = True
                    if not previous:
                        sides += 1  # Left
            
                previous = last_calculated[3]
                last_calculated[3] = False
                if y == cols - 1 or matrix[x][y + 1] != matrix[x][y]:
                    last_calculated[3] = True
                    if not previous:
                        sides += 1  # Right
    return sides

def calcola_angoli(area):
    """ Calcola il numero di angoli di un'area individuata """
    confini = []
    direzioni = [(-1, -1), (-1, 1), (1, 1), (1, -1)]
    direzioni_check = [[(0, -1),(-1, 0)], [(-1, 0), (0, 1)], [(0, 1),(1, 0)], [(1, 0),(0, -1)]]
    for x, y in area:
        i = 0
        for dx, dy in direzioni:
            nx, ny = x + dx, y + dy
            found1 = False
            found2 = False
            if (x + direzioni_check[i][0][0], y + direzioni_check[i][0][1]) in area:
                found1 = True
            if (x + direzioni_check[i][1][0], y + direzioni_check[i][1][1]) in area:
                found2 = True
            if(found1 and found2 and (nx, ny) not in area):
                confini.append((x, y))
            if(not found1 and not found2):
                confini.append((x, y))
            i += 1
    return len(confini)

if __name__ == "__main__":
    input_string = """
CIISIIQQVZZZZZZOOOTTTTTTTTTTTTTTTDDJAAAAADDDDDDDDDDVVVVVVVVMMMMMMMMMMHHHHHJJJHHHHHHVVVVVVVVVVVVVVVVVVVNNNNNNNNNNNNNNNNNNOOOOOOOOOOOOOOOOOOOO
CIIIIIIQVVVZZOOOOOTTTTTTTTTTTTTTDDDDDAGAASDDDDDDDDDDVVVVVVVMMMSMMMMMHHHHHHHJHHHHHHVVVVLLLVVVVVVVVVVVVVYNNNNNNNNNNNNNNNNNNOOOOOOOOOOOOOYYYYYO
CCCIIIXVVVVVOOOOOOOTTTTTTTTTTTTTTDDDDDGGAAAAADDDDDDDVVVVVVVVVSSSSMMMHHHHHHHHHHHHHVVVLLALLVVVVVVVVVVVVVYNNNNNNNNNNNNNNNNNOOOOOOOOOOOYOYYYYYYY
CIIIIIXVCVVVVOOOOOOTTTTTTTTTTTTTDDDDDDDAAAAAAADDDDDDDVVVVVVVVVSSMMMMMMHHHHHHHHHHHHVVLLLLLVVVVVVVVVVVVYYNNNNNNNNNNNNNNNNNOOJJJOOOOYOYYYYYYYYY
CIIIIICCCCVVOOOOOOOOTTTTTTTTTDTTDDDDDDDAAAAAAADDDDDDDVVVVVVVVVVSSSSMMMHHHHHHHHHHHHVLLLLLLLVVVVVVVVVVVYYYNNNNNNNNNNNNNNNJJJJJJJJJYYYYYYYYYYYY
CCCCZZZCCCVOOOOOOOOHHHTTTTTTTDDDDDDDDDDDDAAAAADDDDDDDVVVVVVVVVSSSWWCMMHHHHHHHHVVVLLLLLLLLLVVVVVVVVVVVVVYNCNCCNNNNNNNNNNJJJJJJJJJBYYYYYYYYYYY
CCCCZZZCCCCOOOOOOOOOHHHHTTTTTDTDDDDDDDDDDAAAPDDDDDIIIVZZZVVVVVSSSCCCCCRHHHHHVVVVVLLLLLLLLVVVVVVVVVVVVVVVCCCCCNNNNNNNNGGJJJJJJJJJYYCYYYYYYYYY
CCCCCZCCCCCOOOOOOOOHHHHHHHTTTDTDDDDDDDDDDDDDDDDDDIIIZZZZZVVVVSSSCCCCCCCHHHHHHHHVRLLLLLLLLVLVVVVVVVVVVVVCCCCCCNCNNPPJJJJJJJJJJJJJJJJYYYYYYYYY
CCCCCCCCCCCCOOOOOOHHHHHHHHTTTDTDDDDDDDDDDDDDLLLIIIIIZZZZZIVVSSSSSCCCCCCRHHHHHHHVLLELLLLLLLLVVVBBBBBVVEVCCCCCCCCNPPPJJJJJJJJJJJJJJJJJYYYYYYYY
CCCCCCCCCCCCOOOOOHHHHHHHTTTTTTTDHDCCCCCCCCCDLLZZZZZIZZZZZISVSSSSSSCCCCCRHCHCCGGGGLLLLLLLLLLLLVVBBBBBVVVCCCCCCCCNCCPJJJJJJJJJJJJJJJJJYYYYYYYY
CCCCCCCCCCCOOOOOOOFHHHHTTTTTTDCCCCCCCCCCCCCDDLZZZZZIZZZZZISSSSSSSCCCCCCCCCCCCCCCGGLLLLLZLLYLLVVVBBBBVVLJCCCCCCCCCXJJJJJJJJJJJJJJJYYYYYYYYYYY
CCCCCCCCOOOOOOOOOOOQQQHTTTTLTTCCCCCCCCCCCCCCCCZZZZZZZZZZZISSSSSCCQQCCCCCCCCCCCCCGGLLLLLLLYYVVVBBBBBLLLLJJJJJCCCCCXJJJJJJJJJJJJJJJYMMMYYYYYYY
CCCCCCCOOOOOOOOOOOOQQLLTTLLLLCCCCCCCCCCCCCCCCCZZZZZZZZZZZSSSSLCCCCCCCCCCCCCCGGGGGYSYVVYLYYYVVVLBBBBLLLLJJJJJJJJCCXZJJFJJJJJJJHHHJJMMMMMMMMMY
CCCCCCCCOCOOOOOOOOLLLLLLTLLLLCCCCCCCCCCCCCCCCCZZZZZZZZZZMSSSSLCCCCCCCCCCCCCGGGGGYYSYYYYYYYNNJLLLLBBLLJJJJJJJJJJXXXZXJJJJJJJJHHHHMMMGMMMMMMMY
CCCCCCCCCCCOOOOOOOZLLLLLLLLLLCCCCCCCCCCCCCCCCCZZZZZZZZZZSSSSSLCCCCCCCCCCCCCXXXXGYYYYYYYYYYYJJJJJLLLLLJJJJJJJJJJXXXXXXJJJJJJJHHHHMMMMMMMMMMMX
CCCCCCCCCCCOOOOOOOLLLLLLLLLLLLLLLLCCCCCCCCCCCCZZZZZZZZZZSSSSSSCCCCCCCCCCCCEXXXXYYYYYYYYYYYJJJJJJLLLLLJJJJJJJJJXXXXXXXXXOJJJJHHHHHMMMMMMMMMXX
CCCCCCCCCCCOOOOOOOALLLLLLLLLLLLLLLCCCCCCCCCLLLLZZZZZZZZZSSSSSSSCCCCCCCCCCCXXXXXYYYYYYYYYYYJJJJJJLLLLJJJJJJJJJJXXXXXXXXXXJJJHHHHHMMHMMMMMMQXX
CGGCCCCCCCCOOOOOOOALLLLLLLLLLLLLLLLLLLLRRLRLLLLLLLLLISSSSSSSSSCCCCCCCCCCCXZXXXXYYYYYYYYYYYJJJJJJJLLJJJJJJJJJJXXXXXXXXXXXXXHHHHHHHHHHMMMMMQQQ
FGGGGGGCCCCOOOOOOOLLLLLLLLLLLLLFFFFLLRRRRRRLLLLLLLLIIISSSSSSSSCCCCCCCCNCXXXXXXXXXYYYYYYYYYYYJJJJJLLJLJJJJJJJJJXXXXXXXXXXXXHHHHHHHHHHHHHMMQQQ
GGAGGGGGGCGGOOOOOOOLLLLLLLLLLLLLFFFFFRRRRRRLLLLLLLLIIIISSSSSSSFFCCCACAXXXXXXXXXXXXYYYYYYYYYBJJJJLLLLLJJJJJXXJXXXXXXXXXXXXXXXHHHHHHHHHHHQQQQQ
UUGGGGGGGGGGGOOOOOOOOLLLLLLLLLLFFFFFJJRRRRNLLLLLLLIIIISSSSSSSSFCCHCAAAXXXXXXXXXXXYYYYYBBYYBBJJJJLLJJLJJJJJXXXXXXXXXXXXXXXXZMHHHHHHHHQQQQQQQQ
UUGGGGGGGGGGOOOOOOOOLLLLLLLLLFFFFFFFJJRRRRNLIIIIIIIIIIISZSSSSSHHHHCAAAAAAXIXXXXXXYYYYYBYYYBBJJJJLJJJJJJJJJJXXXXXXXXXXXXPMGMMHHHHHHHHQQQQQQQQ
UUGGGGGGGGGGOOOOOOOOSSLLLLLFLFFFFFFFFFIIORRIIIIIIIIIIIISSSSSSHHHHHHHHHAAAXXXXXXXLLYYYBBBBBBJJJJJJJJJJJJJJJXXXXXXXXXXXXPPMMMMMHHHHHHHHQQQQQQQ
GGGGGGGGGGGOOOOOOOOOOLLLLLLFLLFFFFFFFIIIRRLIIIIIIIIIIISSSSSSSSHHHHHHHHAAAXXXXXXXLYYBBBBBBBBBJJJJJJJJJGGJJJOXXXXXXXXXDXMMMMMMMHHHHHHHHQQQQQQQ
QGGGGGGGGGGOOOOOOOOOOLOOLLFFFFFFFFFFFXIISILIIIIIIIIIISSSSSSSSSAHHHHHMHAAAAXXXXXXLLLBBBBBBBBJJJJJJJJJJJGGGGGXXXXXXXXXDDDMMMMMMHHHHHHHHHQQQQQQ
QGGGGGGGGGGGOOOOOOOOOOOOLLFFFFFFFFFFFFIFIIIIIIIIIIIISSSSSSSSSHAHWHHHHHHAAINXXXXLLLLLLLBBBBBJJJJJJJJJGGGGGGGXXTTXXXXXDDMMMMMMMMHHHHHHHQQQQQQK
UUGGGGGQGGOOOOOOOOOOOOOOFFFFFFFFFPFFFFSSHSIIIIIIIIIISHSSSSSSHHHHHHHHHHHIAIIIXRLLLLLLLLBBBBBBBJJJJJJJGGGGAGGGGXXXHXXDDDBMMMMMMXHHHHHHHHHKKKKK
UUGGGGGUUUUOOOOOAOOOOOOOOFFFFFFFFFFSSSSSSSAAAAAAAAAASSSSSSSSHHHHHHHHHHHIIIIIILLLLLLLLLLBBBBBJJJJJJJTAAFGAGGGGGGGGDDDBBBMMMMMXXXXHHHHHHHKKKKK
UUGGUUGUUUUOOOOOOOOOOOOOOFFFFFFFFFFSSSSSSIAAAAAAAAAASSSSSSSSSSSHHHHHIIWIIIIIILLLLLLLLLLLBBBBJJJJJJAAAAAAAAGGGGGGGGDGBBBBSMMMXXXXHHHHKHHKKKKK
UUUUUUGUUUYOOOONNNOOOOOOOOFFFFFFFFSSFSSIIIAAAAAAAAAASSSSSSSSSSSSHHHIIIIIIIIIILLLLLLLLLLLBBBBJJJJAAAAAAAAAAGGGGGGGGGGBBBSSMMMMXXXXHHKKKHKKKKK
UUUUUUUUUYYOOOONNNOOOOOOOOOOFFFFFFFFFFIIIIAAAAAAAAAASSSVVVVSSSKKKKKKKIIIIIIIILLLLLLLLLLLLRBJJJJAAAAAAAAAAGGGGGGDGDDBBBSSSSMMMXXXXXHKKKKKKKKK
UUUUUUUUUUOOOOOOOOOROOOOOOOOJFFFFFFFIIIIIIAAAAAAAAAAXSVVVVVSSSKKKKKKKAIIIIIIILLLLLLLLLLLLJJJJJJJAAAAAAAAAGGGGGGDDDDDBBBBSXXXXXXXKKKKKKVVKKKK
UUUUUUUUUUOOOOORRROROOOOOOOOJJFFFFFIIIIIIBAAAAAAAAAAAXVVVVVSSSKKKKKKKIIIIIIIILLLLLLLLSSLLLJJJJJJAAAAAAAAAAAGGGGDDDDDFBBBBXXXXXXKKKKKKKKVVVKK
UUUUUUUUULOOOORRRRRRROOOOOOOJJFFFFFIIIIIIBAAAAAAAAAAAXXVVVVVSSKKKKKKKIIIIIIILLLLLLLLLSSSLSSJJJJPPAAAAAAAAAAAAGGGDDDFFFBBBNNXXXKKKKKKKKKVYVVV
UUUUUUUUJJJPPOOJJJRROOOOOOJJJJUUFFFIIIIIIBAAAAAAAAAAAXLLVLLVSSKKKKKKKAAIAIIILLLLLLLLLLSLLPJJRJPPPPAAAAAAAAAAAAGGTDDDDBBBBNNNNXKKKKKKKKKVVVVV
UUUUUUUUJJPPPPPQTJJRRROOOOJJJUUUFUUUIIIBBBAAAAAAAAAARLLLLLLLLLKKKKKKKAAAAAILLRLLLLLLLLPPPPPJJPPPPPAAAAAAAAAAAAATTDDUUBBBBNNNKSSKKKKKKKKVVVVV
UUUUUUUUUTPPPPQQTTJRRRRORJJJJUUUUUUUUIIBBBAAAAAAAAAARLLLLLLLLLKKKKKKKAAAAAARLRLLLLRRRLLPPPPPPPPPPPPAAAAAAAAAAAAATTDDUUBQQNNKKKKKKKKKKVVVVVVV
UUUUUUUUTTPPPPQQQQRRRRRORJJJJUUUUUUUUUUYBBAAAAAAARRRUULLLLLLLLKKKKKKKAAAAAARRRRLRRRRRLRRPPPPPPPPPAAAAAAAAAAAATATTTTTUTBQQQNNKKKKKKKKVVVVVVVV
UUUUUUTTTTTPPPQQQQQQRRRRRRJJUUUUUUUUUUUBBBBBBRAAARRRRULLLLLLLLKKKKKKKAAAAARRRRRRRRRRRRRRPPPPPPPPPAAAAAAAAAAATTATTTTTTTOKKKNNNNKKNTKKVVVVVVVV
UUTUTTTTTTPPPPPQQQQQQQRRBRJJUUUUUUUUUUUDBBBBRRAAARRRRRLLLLLLLLLLLLLAAAAAARRRRRRRRRRRRRRRPPPPPPPPPPPAAAAAAAAAATTTTTTTTTKKKKKNNNNNNKKKVVVVVVVV
UTTTTTTTTTPPPPQQUQQQQQQRRRRJUUUUUUUUUUUBBBBBBBRRRRRRRRRQLLLLLLLLLLLLAAAAAARRRRRRRRRRRRRRRRRRPPPPPPPAAAAAAAAAATTTTTTTTTKKKKKNNNNNNNNVVVVVVVVV
TTTTTTTTTTPPPPQQQQQQQQRRRRRJUUUUUUUUUUUTTBBBBAARRRRRRRRQLLLLLLLLLLLLAAAAAAAFRRRRRRRRRRRRRRRPPPPPPPPPAAAAAAAVAVTTTTTTTTKKKKKKNNNNNNNVVVVVVVVV
TTTTTTTTTTPPPPQQQQQQQQQRZZRRHUURUUKURRRBBBBAAARRRRRRRRRQLLLLLLLLLLAAAAAAAAATRRRRRRVRRRRRRPPPPPPPPPPPTAATTAAVVVTTTTTTKKKKKKKKNNNNNNNVVVVVVVVV
TTTTTTTTPPPPPPPQQQQQQQQQZZRRRRRRRUUURRRRBBBAAARRRRRRRRQQLLQLLLLLLAAAAAAAAATTRRTRTVVRRRRCCCPPPPPPZZPPPPTTTVVVVVVTVTTTTKKKKKKKNNNNNNNVVVVVVVVV
TTTTTTNUPPPUUPPPQQQQQQQQZZRRRRRRRRUURRRRRRRRRRRRRRRRRRQQQQQLLLLLLAAAAAAAATTTTTTTTVVRRRRRCCPPPPPPZTPPTTTTTQQVVVVVVVVKKKKKKPPKKGGGGNVVVVVVVVVV
TTTTTTNUUUUUUPPQQQQQQQQQQQUURRRRRRRURRRRRRRRRRRRRRRRRQQQQQQQLLLLLLLAAAAAATTTTTTTVVVVVRRVCCCPCCCPPTTPTTTTTQQQVVVVVVVKKKUKKPPPPGGGGTVVVVVVVVVV
TTNNNNNUIUUUUUPPQQQQQQQQQUUURRRRRRRRRHHHRRRRRRRRRRRRRRQQQQQLLLLLLLLXAAAAATTTTTTTVVVVVRTVCCCCCCCPPTTPTTTTTTQQVVVVVVVKKKKKPPGGGGGGGTVVVVVVVVVV
NTTNNNUUUUUUUUUUUTQQQQTQUUUUURRRRRRRRHHRRRRRRRRRRRRRRRQQQQQLLLLLLLLAAAATTTTTTTTTTTVVVVVVVCCTCTTTTTTTTCTTTQQQQVVVVVVKKKKVPGGGGGGGGVVVVVVVVVJJ
NTTNUUUUUUUUUUUUUUHUTTTTXXUXURRRRRRRRHRRRRRRRRRRRRRRRRRQQQQQLLLLLLFAAAAAFFTTTTTTTTVVVVVVVCCTTTTTTTTTTCTTZCQQQVVVVVVVKVVVVHHGGGGGGVVVVVVVVJJJ
NNNNNUUUUUUUUUUUUCUUUTTTXXXXURRRRHRRRHRRRRRRRRRRRRRRRRRRQQQLLLLLFFFFAAAAFFTTTTTTTTVVVVVVVVCTTTTTTTTTTCCCCCCCVVVVVVVVVVVVQQQQGGGGGGVVVVJJJJJJ
NNNNNUUUYUUUUUUCCCUUUUUXXXXXXYYRYHHHHHRRRHRRRRRRRRRRRRRRQQQLFFFFFFFFAAAFFTTTTTTTTEVVVVVVVCCCCNNTTTTTTCCCCCCCJVVVVVVVVVQQQQQGGGGGGGGGGJJJJJJJ
NNNNNNUUUUUUUUCCCCCUUUUXXXXXYYYRYYHHHHRHHHRRRRRRRRRRRRRRQQFFFFFFFFFFFFFFFFTTTTTTTEVVVVVVCCCCCCNTTTTTCCCCCCCJJVVVVVVVVQQQQQQQGGGGGGGGUJJJJJJJ
NNNNNNNUUUUUUUCCCCUUUUUXXXXXYYYYYYYHHHRHHHHRRRRRRRRRRRQQQFFFFFFFFFFFFFFFFFFTTTTTEEEEVVCVCCCCCNNNNTTTCCCCCCCCJCVVVVVVVVQQQQQQQQQGGGUQUUUUUUJJ
NNNNNNNUUUUUUUCCCCUUUXUXXXXXYYYYYYYHHHHHHHHHHHRRRORRQQQQQFFFFFFFFFFFFFFFFEEUTTEEEEECCCCVCCCCCCNNTTTTCCCCCFCCCCCVVVVVVVVQQQQGGQGGGGUUUUUUJJJU
NNNNNNNNUUUUUCCCCUUUUXXXXXXLYLLLYYYHHHHHHHHHHHRRQQRQQQQQQFFFFFFFFFFFFZFFFEEEEEEEEEEEECCCCCCCNNNTTTCCCCCCCCCCCCVVVVVVVVVVNQQGGGGIGUUUUUUUUUUU
NNNNNNNJDDUUUCCUUUUUUXXLXXLLLLLLLYYYHHHHHHHHHHRRQQQQQQQQQFFFFFFFFFFZZZFFFEEEEEEEEEEECCCYCCCNNNNNNCCCCCCCCCCCCIIVVVVVVVVVQQQGGIGIIIUUUUUUUDEE
JJNNNJJJJJUQUCCCCUUXXXLLLLLLLLLLLLLLFFHHHHBBBRRRBQQQQQQQFFFFFFFFFZFFVZZFFEEEEEEEEEEEYYYYYYCCYNNNNUUCCCCCCCCCCCLLVVVVVVVVQFFIIIIIIIIIUUBBEEEE
JJJNNJJJJJUJUCCCCUUUXXLLLLLLLLLLLLFFFHHHHBBBBBBBBBQQQQQQQQFFFFFFZZFZZZZZEEEEEEEEEEEEEYYYYYYYYUUNUUUUUUCCCCCLLLLLLLLLVVFFFFFFIIIIIIIIUUBEEEEE
JJNNJJJJJJJJJCCCCCUCXXLLLLLLLLLLLLFFFHHHHBBBBBBBBBBBQQQQQFFFFFFZZZZZZZZZEEEEEEEEEEEEEIYYVVVUUUUUURUUUUCCCCCLLLLLLLLLLLFFFFFFIIIIIIJJJJJEEEEE
JJJJJJJJJJJJJCCCCCCCXCLLLLLLLLLLLLFFFHHHHHHBBBBBBBBBIBQQQQFFWWZZZZZZZZZEEEEEEEEEEEEEEEYYVVVDUUUUURRUUUACCCCLLLLLLLLLELFFFFFFIFIIJIJJJJEEEEEE
JJJJJJJJJJJJCCCCCCCCCCCLLLLLLLLLLLFFFFFHHHBBBBBBBBBBBBQWWQWFWWWWZZZZZZZZZZEEEEEEEEEEEWYYVVVUUUURRRRRUUUCBBLLLHLPLLLLLFFFFFFFFFIIJJJJJJEEEEEE
JJJJJJJJJJJCCCCCCCCCCCCLLLLLLLLLLLFHFHHHHHHBBBBBBBBVBWWWWWWWWDDDDDZZZZZZZZEEEEEEEEEEEWWWVVVWUVVVVVRRRUUBBLLLLLLLLBLPPPFFFFFFJJIIJJJEEEEEEEEE
JJJJJJJJJJJCCCCCHHCCCCCLLLLLLLLHHHHHHHHHHHHBBBBBBBBVFFWWWWWDDDDDDDZZZZZZZZXXEEEEEEWWEWWWVVVWUVVVVVBBBUUBLLLLBBBBBBBPPPFFFFJJJJJJJJJJEEEEEEEE
JJJJJJJJJJJCCCCCHHHCCCCCCCLLLLLHHHHHHHHHHHHHIBBBBHBVFFFWWWJDDDDDDRZZZZZZZZXXXEEEUEEWWWPPVVVWWVVVVVQBBUBBBBBBBBBBBBBBPPPPPPPSJJJJJJJJEEEEEEEE
JJJJJJJJCJRRCCCCHHHHHCHCCCCLLLLLHHHHHHHHHIIIIBHHHHHFFFFWWDJJDDDDDDZZZZZZZZZUXUUUUUUPPPVVVVVVVVVVVVPBBBBBBBBBBBBBBBBBPPPPPPPJJJJJJJJEEEEEEEEE
PJJJJJJCCRRRRCCHHHHHHHHCCCCLLLLLHHHHHHHHHHHIIIIIIIHHHFWWWDJJJDDDDDDZZZZZOOUUUUUUUUUPPPVVVVVVVVVVVVPBBBBBBBBBBBBBBBBPPPPPPPPPJJJJJJJLLEEEEEEE
PJJJJRRRRRRRRRHHHHHHHHHCCCCLLLMHHHHHHMHHHHHIIIIIIIFFHFFFWDJJDDDDDDDDZOOOOOOOUUUUUUUPVVVVVVVVVVVVVVPBBBBBBBBBBBBBBBBPPPPPPPPPPJGJJJJLLLLLLEEM
PPJRRRRRRRRRRRHHHHHHHHCCCCCEEEKHKKHKHMHMHHIIIIIIIIFFFFJFDDDDDDDDDDDOOOOOOOOOUUUUUUUPVVVVVVVVVVVVVVPBBBBBBBBBBBBBBBBBBPEPPPOPGGGGGDJLDLLLLMMM
PPRRRRRRRRRRRRRRHHHHHHCCCCEEEKKKKKKKMMMMMMIIIIIIIIFFFFFFFDDDDDDDDDDOOOOOOUUUUUUUUUUUVVVVVVVVVVVVVVABBBBBBBVVVBBBBBBBBPPPPPPPGGGGDDDDDDLLMMMM
PPRRRRRRRRRRRRRRRRRHEECCCEEEKKKKKKKKCMMMMMIIIIIIIIFFFFFFFDDDDDDDDDOOGGGOOUUUUUUUUUUUVVVVVVVVVVPVVVAAABBBBVVVVVBBBBBBPPPPPPPPGGHHDDDDLLLLMMMM
PRRRRRRRRRRRRRRRRRREEEECCEEEKKKKKKKCCKMMMIIIIIIIIIIFFFFFFDDDDDDDDDOOOGGGGGUUUUUUUUUPVVVVVVVVVVPVVVAAAABBBBVVVVVVVVVVSSSPPPGGGGHHGDGDDLLLMMMM
PPPPRRRRRRRRRRRRRRREEEEEEEEEKKKKKKKKKKMMMEIUUIIIIIIFFFFFCDDDDDDDDDOOOGGGGGUUUUUUUUUPVVVVVVVVVVQQQQAAAABBBBVVVVVVVVVPVSSPPPPPGGGGGGGLLLLLMMMM
PPPPRRRRREERRRRRRREEEYYYYYYYYKKKKKKKKKMMMESUSSSSIILFFFFFCCDDDDDDDDOOOGGGGGUUUUUUUUUPVVVVVVVVVVQQQQAAABBBBBYVVVVVVVVVVSSSSSSGGBGGGGLLLMMMMMMM
PPPPRRRREEEEERRRRREEEYYYYYYYYKKKKKKKKKMMMESSSSSSSIISFFCCCJNDDDDDDDDOOGGGGGGGUUUUUUGGPVVVVGPPPQQAAAAAABBBBBBBJVVVVVVVVVVVSSGGGLLLLLMMMMMMMMMM
PPPPPPREEREEERRRRRREYYYYYYYYYYKKKKKKKKKMEESSSSSSSSSSSSCCJJJDDNDDDDOOOYGGGGGGGUUGGGGGGVVVVPPPPQQQAAAAAABBZZVVVVVVVVVVVVVVSSSSSLLLLLMMMEMMMMMM
PPPPPESEEEEEEERERRRRIYYYYYYYYYKKKKKKKKKSSSSSSSSSSSSSSSCCJJCDDDDDDDDYYYGGGGGGGGGGGGGGGGGGGGPPQQAAAAAAAAAAZZZZVVVVVVVVVVSSSSSLSLLLLLLJLMMVVMMP
PPPPEEEEEEEEEEEEERRKYYYYYYYYYYYKKKCKKKKCCSSSSSSSSSSSRCCCJJJDDDDDYUUUUYYYGGGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAZZZZZVZCCCVVVVSSLLLLLLLLLLLLLVVVVMM
PPPPEEEEEEEEEEEEEERRRLYYYYYYYYYKKCCCCCCCSSSSSSSSSSSSRCCCCJJDDDDDYYYYYYYYYGGYGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAZZZZZZCCZZVFLSLLLLLLLLLLLLLVLVVVV
PPPPEEEEEEEEEEEEEELLLLLYYYYYYYYCCCCCCCCCSSSSSSSSSSSSRRRRRJSDCDDDDJJYYYYYYYYYYYYGGGGGGGGGGGGAAAAAAAAAAAAAAAZZZZZZZZCZLVVLLLLLLLLLLLLLLLVLLLUU
PPPEEEEEEEEEEEEEELLLLLLLYYYYYCCCCCCCCCCCCSSSSSSSRRRRRRRRRRRRRDNNDYYYYYYYYYYYYYYGGYGGGGGGGGGAAWWAADAAAAAANNNZZZZZZZZZLLVLLLLLLLLLLLLLLLLLUUUU
SPPEEEEEEEEEEEEELLLLLLLLYYYYCPCCCCCCCCCCCCCCSSSRRRRRRRRRRRRCCDPPPYYYYYYYYYYYYYYYYYYYYGGGGGGGWWAAADDAAAAANNNZZZZZZZZZZLLLGGGLLGLLLLLLULLLUUUH
SPPEEEEEEEEEEEEELLLLLLLLVVYYCCCCCCCCCCCCCCCCCSSRRRRRRRRRRRRCCCPPYYYYYYYYYYYYYRYYYYYYYGGGGGGIAAAAADDAAAAANZZZZZZZZZZZZGGGGGQQQGLLLLLLUUUUUUUU
SSNEEEEEEEEEEEEEELLLLLLLLVVCCCCCCCCCCCCCCCCSSSSRRRRRRRRRRRRRRPPPPPPYSYYYYYYYYRRRYYYYYGGGGGIIIEEDDDDEAANNNZZZZZZZZZZZZZGAGGGGGGGLLLLLUUUUUUUU
SNNNNNNNEEEEBBBBBBLLLLLLLVVVVVVCCCCCCCCCCCCSSSSRRRRRRRRRRRRJJPPPPPPPSSSYYYYYRRRRRRYYYGYYYZZZZZZZZZDEAAANNZZZZZZZZZZZZAAAGGGGGGGLLLLLUUUUUUUU
SNNNNNNNEEESSBBBBBLLLLLVVVVVVVVCCCCCCCMCCCSSSSSRRRRRRRRRRRRPPPPPPPPPPPSYYYYYRRRRRRYYYYYYYZZZZZZZZZJJJJANNZNZZZNZZZIIIGGGGGGGGGGGLLLKKUUUUUUU
SSNNNNNNSEEEBBBBBBEEELVVVVIVVVVMIICCCMMCCCCSSSSRRRRRRRRRRRAPPPPPPPPPPPSSSRRRRRRRRYYYYYYYYZZZZZZZZZZZZZNNNNNNNNNNIIISIIGGGGGGGGFFLLKKKKUKUUUY
SSNSSNNSSSSBBBBBBBBBGGGGGVIIVMMMICCCMMMMMMSSSSSRVRRRRRRIRRPPPPPPPPPPPRRSSRRRRRRRRYYYYYYYYZZZZZZZZZZZZZEEENNNNNNNIISSSGGGGGGGGGGGLLKKKKKKXXXX
SSSSSSSSSSSSBBBBBBBGGGGGVVVIIMMMMMMMMMMMMMMSSSSSSSRRRRRRRPPPPPPPPPPRRRRRRRRRRRRRRRYYRRYYYZZZZZZZZZZZZZEEENNNNNNNNNSSSSGGGGGGGGGDLKKKKKXXXXQX
SSSSSSSSSSSSBBBBBBBGGGGGGGGGGMMMMAMMMMWWMMMMSSSKSSRRRRRRPPPPPPPPPPPPTRRRRRRRRRRRRRRRRRYYYKKKZZZZZZZZZZEEUNNNNNNNNNSSSUUUUUUUUUGGXKKKKKXXXXXX
SSSSSSSSSSSSBBBBBBBGGGGGGGGGJMMMAAAMMWWWWMMMMWSSIIRRRRRRRPPPPPPPPPPPPRRRRIRRRRRRRRRRRRYYYOKKZZZZZZZZZZEEUUNNNNNNNNSSSUUUUUUUUUGGKKKKKKXXXXXX
SSSSSSSSSSBBBBBBBBBGGGGGGGGGMMMMAAAMMJJWWWMMMSSSIIIIRRRPPPDDDPPPPDPPPIIIIIRRRRRRRRRRRHYOYYXKZZZZZZZZZZEUUUNNNNNNSSSSSUUUUUUUUUGKKKKKKKXXXXXX
SSSSSSSSSSBBKBBBBBBGGGGGGGGYYYYYYYJJJJJJJMMMMMSLLLIIRRRPPPDDDDDDDDDIIIIPIIIRRRIRRRRRRRRYYYYKZZZZZZZZZZUUUUTTTUNNSSSSSUUUUUUUUUZKKKKKKKXXXXXX
SSSSSSSSSSSSBBBXXBBGGGGGGGYYYYYYYYJJJJJJJJJJJLLLIIIIRRRPPPDDDDDDDDDDIIIIIIIRRRIRRRRRRRRRYYQKRREEEZZZZZQQQQUUUUUSSSSSSSZUUUGGZZZKSKKKKKXXXXXX
SSSSSSSSSSAABBXXXXGGGXEGGYYYYYYYYYYJJJJJJJJJJLLLIIIIRRPPPPDDDDDDDDIDIIIIIIIIIIIRRRRRRRRRRERRRREEEZZZZZQQQQUUUUUUUUUUUUUUUUZZZZZSSSSSSSXXXXXX
SSSSSSSSSAAAXXXXXXXXXXXYYYYYYYIIYPPPJJJJJJJJLLLLLIIIRRRPPPDDDDDDDDIIIIIIIIIIIIIIIRRRRRRRSRRRRPEEEZZZZZQQQQUUUUUUUUUUUUUUUUZZZZZSSSSMMSXXSEXL
SGSSSSSSAAAAXXXXXXXXXXZYYYYBYYPPPPPJJJJJJJLLLLLLIIIIILLPPPPDDDDDHIIIIIIIIIIIIIIIIRRRRRRRRRRRRRREEEEQUQQQQQUUUUUUUUUUUUUUUUZKZZSSSSSSSSXSSSLL
GGSSSSSAAAAAAXXXXXXXXXZYYYYYYYPPPPSXMJJLLLLLLLLLLLIIIILPPPDDDDDDHDIIIIIIIIIIIIIYIRRRRRRRRRRRRRREEEEEQQQQQQUUUUUUSSSWWKKKKKKKZZSSSSSSSSSSSSLL
GGGSSSSAAAAAAXXXXXXXXXXXYYYYYPPPPXXXXXJZXLLLLLLLLLLIIILLLLLDDDDDDDAAIIIIIIIIIIIIRRRORRRRRRRRRRREEESEUQQQQQUUUUUUNSSSWKKKKKKKKSSSSSSSSSSSSSLL
GGGSSSSAGAAAGXXXXXXXXXYYYYYYYPPPPPPXXXXXXXBLLLLLLLLIIILLLLLLDDDDLWLAIIIJIIIIIIIIRRROYYRRRRRRRREEWRREUQQQQQUUUUUUNSSWWKKKKKKKKSSSSSSSSSSSSSLL
GGGGGSSAGAAAGXXXXXXXXXXXYYYYXPPPPXXXXXXXXXBLLLLLLLIIIILELLLDDDDDLLLAAIIIIIIIOOOOOOOOOORRRRRRRRRRRRRWWQQQQQNNNNNNNNVWWKKKKKQQQQQSSSSSSSSSSLLL
GGGGGGSGGGAAGXXXXXXXXXYYYYYYXXPXXXXXXXXXXXBBLLLLLLFFFILLLLLLLLLDLLLLLWWIHIHOOOOOOOOOOORRRRRRRRRRRRRWWQQQQQNNNNVNNVVWWWKKKKKKKQQSSSSRRRSSSSSS
GGGGGGGGGGGGGXXXXXXXXXXXXYYYXXXXXXXXXXXXXXXLLLLLLLFFLLLLLLLLLLLLLLLLWWWRHHHOOOOOOOOOOOOORRRRRRRRRRRWWWWWWNNNNNVVVVVVKKKKKKKKKKQQSRRRRRRRRSOO
GGGGGGGGGJJGGXXXXXXXXXXXXYYYXXXXXXXXXXXXXXLLLLLLLLFFLXLRRLLLLLLLLLLLRWRRHHHHOOOOOOOOOOORRRRRRRRRRRWWWWWWWNNNNNVVVVVVVVXKKKKKKKIIRRRRRNNNRNON
GGGGGGGGGJJJGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXLLXXXXXXXXXRRRRLLLLLLLLLRRRRRHHHOOOOOOOOOOOOMYRRRRRRRRRWWWWWWWNNNNNNVVVVVVVKKKKKKKIIIRIRRRNNNNNON
GGJGJJGJGJJJJVXXXXXXXXXXCXZXXXXXXXXXXXXXXXXXLWXXXXXXXXRRRRLLLLLLLLLLRRRRHHAAOOOOOOOOOOJYYRRRRRRRRWWWWWWWWNNNNNNVVVVVVVKKKVVVVIIIIIRRNNNNNNNN
GGJJJJJJJJJJJJOOXXYXXXXLLLZXXXXXXXXXXXXXXXXWWWXXXXXXXXXRRRSSSLSSLLLLLRRRRAAAMMMMOOOOOOYYYYSRRRRWWWWJJWWWWWJNNNNVVVVVVVVVKVVVVIIIIIIIFNNNNNNN
GGGGJJJJJJJJJJJXXXXXXXLLLLLXXXXXXXXXXXXXXXXWWWXXXXXXXXXXXXSSSSSSSSLLRRRRRAAAAOOOOOOOOYYYYYYRYRYWYWWJJJJJJJJYYYVVVVVVVVVCKVVVVIIIIIIIINNNNNNN
GGGJJJJJJJJJJJLXXLXXXLLLLLLLXXXXXXXXXXXXWXXWWWWXXXXXXXXXXDDNNNSSSRRRRRDAAAAAOOOOOFOOYYYYYYYYVVVVVYJJJJJJJJJYYYVVVVVVVVVCSSSSSSSSSSSSSNNNNNNN
GGJJJJJJJJJJJJLLLLLXLLLYYYLLXXXXXXXXXXXXWXWWWWXXXXXXXXXXXXXXNNNSSSRRRRAAAAAOOOAOOOOOOYYYYYYYVVVVVJJJJSSSSSSSSSSVVVVVVVVVSSSSSSSSSSSSRRNNNNNN
GGGJJJJJJJJJJJJLLLLLLYLLYYFLXXXXXXXXXXWWWWWWWXXXXXXXXXXXXXXXNNNNSRRRRRAAAAAAAAAAOOOYYYYYYYYYVVVVVVJJJSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSRNNNNNNN
GGGJJJJJJJJJJJJLLLLLLYYYYYFFXXXXYXHXXXXXWWWWWWWXXXXXXXXXXXXSNNNNSSRRRRRSFFFAAAAAAAAYYYYYYYYYVVVVVVVVVSSSSSSSSSSSSSSSSSSSSSSRRIIIIBRRRNNNNNNN
GJJJJJJJJJJJJLLLLLLLYYYYYYYFFXWWNNNXXXXXWWWWWWXXXXXXXXXXXXSFFFFFFFFFRSSSFFFAAAAAAASYYYYYYYYYVVVVVVVVVSSSSSSSSSSSSSSSSSSSSSSRRRRRIRRRRRNNNNNN
JJJJJJJJJJJJJLLLLLLYYYYYYYYFNNNNNNNXXXWWWWWWWWWXXXXXXXMVXXSFFFFFFFFFFFFFFFFAAAAAASSSSYYYYYYYVVVVVVVVVVVVSSSSSSSSSSSSSSSSSSSRRRRRRRRRRRRRNNNN
PJJJUJJJJLLJJLLLLLLLYYYYYYYYYNNNNNNXXXWWWWWWWWWWXXXXXXVVVXSFFFFFFFFFFFFFFFFFFFFFFFFFIUYYYYYYVVVVVVVVVVVVVVVSSSSSSSSSSSSSSSSCRRRRRRRRRRRRNNNN
JJJJJJJJJJLLLLLLLLLLLLYYYYNNNNNNNNNWWWWWWWWWWWWWXXXXXVVVSSSFFFFFFFFFFFFFFFFFFFFFFFFFUYYYYYYYVVVVVVVVVVVVVVVSSSSSSSSSSSSSSSSRRRRRRRRRRRRRWNNN
JJJJZZZAALLLLLLLLJLJLLYNNNNNNNNNNNNWWWWWWWWWWWWWXXXXXVVVVSSFFFFFFFFFSSFFFFFFFFFFFFFFUYYYYYYYYYCICJVVVVVVVVVSSSSSSSSSSSSSSSSRRRRRRRRRRRWWWNNW
JJJYAZAAAAALLJLLJJJJJJJNNNNNNNNFFFNWWWWWWWWWWXXXXXXVVVVVSSYFFFFFFFFFSSFFFFFFFFFFFFFFUUUYYYYYYYCCCCJJCRVVVVVVMMMMMMMMMMXXRRRRRRRRRRRLRRLWWWWW
AAJAAAAAAAAJJJLJJJJJNNNNNNNNNNFFFFFFFFWWWWWWXXXXXXXXVVVVSSSFFFFFFFFFSSSZFFFFFFFFFFFFIIUUYYYYCCCCCCCCCCJJJVVVMMMMMMMMMLMMMMMRRRRRRRRLRRLLLWWW
AAAAAXAAAAAJJJLJJJJTJJNNNNNNONNSFFFFFWWFFFNWXXXXXXXVVVVVSSYFFFFFFFFFZSSZFFFFFFFFFFFFIIIUYYYYZCCCCCCCCCBBJVVVWMMMMMMMMMMMMMMMRRRRRRLLLLLLLWWL
EEAAAAAAAAAJJJJJJJJJJJNNNNNNONNNFFFFFFWFNFNNNNXXXXXXVVVVVVVYYHUUUUUZZZSZZZFFFFFFFFFFZIIIYYYTTTCCCCCCCBBCHVVVWWWMMMMMMMMMMMMMRRRRRRLLLLLLLLLL
EEAAAAAAAAAJJJJJJJQQNNNNNNNNOOFFFFFFFFNFNFNNNNNXXXVVVVVVVVVYYUUUUUUUZZZZZZZZZIZZZZZZZIITTYTTTTCCCCCCCCCCHVVVWWWWWMMMMMMMMMMMMRRRRLLLLLLLLLLL
EEAAAAAAAAJJDJJJJJJQQNNNNNNNOOFFFFFFFFNNNNNNNNXXXXVVVVVVVVVYYYUUUUUZZZZZZZZZIIZZZZZZZSTTTYTTTCCCCCCCFCCHHVVVEWWWWMMMMMMMMMMMMMRRRRLLLLLLLLLL
EAAAAAAAAAJDDJJJJJJQQQQNNNNNOOFFFFFFFFNFFNNNNNXXXXVVVVVVVVVYYYUUUUUUZZZZZZZZZIZZZZZZZSSTTTTTTCCCCCCCCCCCHVVVWWWWMMMMMMMMMZZZRRRRRRRLLLLLLLLL
EEEAAAAAAJJJJJJJJJJJQQQQNNNNFFFFFFFFFFFFFNNNXXXXXXVVVVVVVVVYYUUUUUUUZZZZZZZZZIZZZZZZZSSTTTTTTCCCCCCCCCEEEVVVWWWWWMMMMMMMMZZZRZRRRRLLLLLLLLLL
EEEAAAAAAABJJJJJJJJQQQQQQNFFFFFFFFFFFFFFFNNNXXXXXXXVVVVVVYYYYYYUEEUZZZZZZZZZZZZZZZZZZZZZZTTTTCCCCCCCCCEEEVVVWWWWWWMMMMMMZZZZZZZRRRLLLLLLLLLL
EEEEAAAAAAAJJJJJJJJJQQQQQNNNFFFFFFFFFFFFFXXXXXXXXXXXVUVVVVYYYYYYZZZZZZZZZZZZZZZZZZZZZZZZZTTTTCCCCCCCCCEERREMRRRWWMMMMMZZZZZZZZZZRRLLLLLLLLLL
EEEEEAAAAAAAAJJJJTJQQQQQQNNFFKKFFFFFFFCCCCXXXXXXXXXXVVVVVYYYYYYYZZZZZZZZZZZZZZSZZZZZZZZZZTTTCCCCCCCCCCERRRRRRRRWWWWMMMZZZZZZZZZRRRLILLLLLLLL
EEEEAAAAAAAAPPPJJRQQQQQQQQQKKKKKKFFFFFFCCCCXXXXXXXXXXXYVVYYYYYYYZZZZZZZZZZZOZZZZZZZZZZZZZTTTTCCCCCCCCEERRRRRRRRRRWWMMMZZZZZZZZZZIIIIIILLLLLL
EEEEAAAQCCAAPPPPRRRRQQQQQQQKGGKXKFFFFCCCCCCCXXXXXXXYYYYYYYYYYYYZZZZZZZZZZZZSZZZZZZZZZZZZZTTTCCCCCEEEEEEEERRRRRRRRRWWWMZZZZZZZZZZZIIIIIILLLLL
EEEEEEECCCCPPPPPRRRURQQRQQQKGKKKKKKFCCCCCCCCCCCCCCXXXYYYYYYYYYYYYZZZZZZZZZZZZZZZZZZZZZZZZTTTCTTTCEEEEEEERRRRRRRRRRWWWWZZZZZZZZZZIIIIIIILILLL
EEEEEEECCCCPPPPRRRRRRRRRQQQKKKKKKKKCCCCCCCCCCCCCCCCNYYYYYYYYYYYZZZZZZZZZZZZZZZZZZZZZZZZZZSTTTTTTTTTEEEEERRRRRRRRRRRWWWZZZZZZZZZZIIIIIIAIILLL
EEEEEEEEEEEEPPRRRRRRRRRRQQQKKKKKKKKXXCCCCCCCCCCNCCCNYYYYYYYYYYYZZZZZZZZZZZZZZZZZZZZZZZZZZSSTTSTTSSEEEEEERRERRRRRRRXWWZZZZZZZZZAZIIIIIIIIIILL
EEEEEEEEEEEKRRRRRRRRRRLRKKKKKKKKKCXXXCCCCCCCCCCNCCCNYYYYYYYYYYYZZZZZXXZZXXXXZZZZQSSSSSSSTTTTSSSSSSSSEEEEEEERLRRRRRWWWWWZZZZSZZZIIIIIIIIIXXXL
EEEEEEEEEEFRRRRRRRRRRRRTKKKKKKKKCCCXXCCCCCCCCCCNNNNNNXXXXXXYYYYYQQUXXXXXXXXXZZZZZZZZZZSSSTTTSSSSSSSSSEEEEELLLLRRRRRWWJPZSSSSZZIIIIIIIIIIXXXX
EEEMEEEEEEFFFRRRRRRRRRTTKKEKKKKKKCCCCCCCCCCCCCNNNNNNXXXXXXXXXXXXQQUXXXXXXXXXZZZZZZZZZZSSCTTTTUSSSSSSEEEEEELLRRRRRRRJJJJSSSZZZZIIIIIIIIIIXXXX
EEEMMEEEEEFFRRRRRRRRRRRKKKKKKCKCCCCCWCCCCCCCCCCCNNNNNNNXXXXXXXXXQQQQXXXXXXXXZZZZZZZZZZSCCTTTTTTEESSEEEEEEEEEERRRJRRJJJJJSSSZZSIIIIIIIIIIXXXX
MMMMMMMMEEERRRRRRRRRRRDDDKKKKCCCCCCCCCCCCCCCCCNNNNNNNNNNXXXXXXXQQQQQQQXXXXXXXXOZZZZZZZSSSTTTTTTEEEEEEEEEEEEEEREJJAJJJJJJSJSSSSIIIIIIIIIXXXXX
MMMMMMMMEKKRRRRRRRRRRRDDDDKKKCCCCCCCHCCCCCCCCCNNNNNNNNNNXXXXXXXQQQQQQQNNXXXXXXOZZZZZZZSSRTTTTTTEEEEEEEEEEEEEEEEJJJJJJJJJJJSSSSSIIIIIIIXXXXXX
OMMMMMMKKKKKRRRRRRRRRRDDDDKKKKCJCCCCHCCCCCCCCCCNNNNNNNXXXXXXXXXQQQQQQQQQQXXXXXOZZZZZZZIITTTTTTTTTEEEEEEEEEEEEEEEEJJJJJJJJJSSSSIIIIIIIIXXXXXX
OOOMMMKKKKKKKRRRRHRRRDDDDDKKKCCCCRCHHHHCCCCCCCCCNNNNNNNXXXXXXXQQQQQQQQQQQQQXXXXOOOOOIIIIITTTTTTEEEEEEEEEEEEEEEEEEJJJJJJJJSSSSSSSIIIIXXXXXXXX

"""

#     input_string = """
# AAAAAA
# AAABBA
# AAABBA
# ABBAAA
# ABBAAA
# AAAAAA
#     """
    matrix = read_matrix_from_string(input_string)
    #print_matrix(matrix) 
    
    areas = find_areas(matrix)  # Find all connected areas
    print("\nAreas found:")
    total = 0
    for idx, (letter, positions) in enumerate(areas, start=1):
        area_size = calculate_area(positions)
        #perimeter = calculate_perimeter(matrix, positions)
        #sides = calculate_sides(matrix, positions)
        corners = calcola_angoli(positions)
        #corners = calculate_corners(matrix, positions)
        total += area_size * corners
        print(f"Area {idx}: Letter '{letter}', Size: {area_size}, corners: {corners}")
    print(f"Total cost: {total}")